"""Initial migration

Revision ID: 0001
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('opening_stock', sa.Float(), nullable=True),
    sa.Column('safety_stock', sa.Float(), nullable=True),
    sa.Column('monthly_forecast', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_material_active', 'materials', ['is_active'], unique=False)
    op.create_index('idx_material_category', 'materials', ['category'], unique=False)
    op.create_index('idx_material_code', 'materials', ['code'], unique=False)
    op.create_index(op.f('ix_materials_code'), 'materials', ['code'], unique=True)
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)
    
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vendor_active', 'vendors', ['is_active'], unique=False)
    op.create_index('idx_vendor_code', 'vendors', ['code'], unique=False)
    op.create_index(op.f('ix_vendors_code'), 'vendors', ['code'], unique=True)
    op.create_index(op.f('ix_vendors_id'), 'vendors', ['id'], unique=False)
    
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_number', sa.String(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_offer_date', 'offers', ['delivery_date'], unique=False)
    op.create_index('idx_offer_material', 'offers', ['material_id'], unique=False)
    op.create_index('idx_offer_number', 'offers', ['offer_number'], unique=False)
    op.create_index('idx_offer_status', 'offers', ['status'], unique=False)
    op.create_index('idx_offer_vendor', 'offers', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_offers_id'), 'offers', ['id'], unique=False)
    op.create_index(op.f('ix_offers_offer_number'), 'offers', ['offer_number'], unique=True)
    
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('expected_delivery', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_po_date', 'purchase_orders', ['order_date'], unique=False)
    op.create_index('idx_po_material', 'purchase_orders', ['material_id'], unique=False)
    op.create_index('idx_po_number', 'purchase_orders', ['po_number'], unique=False)
    op.create_index('idx_po_status', 'purchase_orders', ['status'], unique=False)
    op.create_index('idx_po_vendor', 'purchase_orders', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_id'), 'purchase_orders', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sa.String(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('receipt_date', sa.DateTime(), nullable=False),
    sa.Column('batch_number', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_receipt_date', 'receipts', ['receipt_date'], unique=False)
    op.create_index('idx_receipt_material', 'receipts', ['material_id'], unique=False)
    op.create_index('idx_receipt_number', 'receipts', ['receipt_number'], unique=False)
    op.create_index('idx_receipt_po', 'receipts', ['purchase_order_id'], unique=False)
    op.create_index('idx_receipt_vendor', 'receipts', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_receipts_id'), 'receipts', ['id'], unique=False)
    op.create_index(op.f('ix_receipts_receipt_number'), 'receipts', ['receipt_number'], unique=True)
    
    op.create_table('consumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consumption_number', sa.String(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('consumption_date', sa.DateTime(), nullable=False),
    sa.Column('project', sa.String(), nullable=True),
    sa.Column('cost_center', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_consumption_date', 'consumptions', ['consumption_date'], unique=False)
    op.create_index('idx_consumption_material', 'consumptions', ['material_id'], unique=False)
    op.create_index('idx_consumption_number', 'consumptions', ['consumption_number'], unique=False)
    op.create_index('idx_consumption_project', 'consumptions', ['project'], unique=False)
    op.create_index(op.f('ix_consumptions_consumption_number'), 'consumptions', ['consumption_number'], unique=True)
    op.create_index(op.f('ix_consumptions_id'), 'consumptions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consumptions_id'), table_name='consumptions')
    op.drop_index(op.f('ix_consumptions_consumption_number'), table_name='consumptions')
    op.drop_index('idx_consumption_project', table_name='consumptions')
    op.drop_index('idx_consumption_number', table_name='consumptions')
    op.drop_index('idx_consumption_material', table_name='consumptions')
    op.drop_index('idx_consumption_date', table_name='consumptions')
    op.drop_table('consumptions')
    op.drop_index(op.f('ix_receipts_receipt_number'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_id'), table_name='receipts')
    op.drop_index('idx_receipt_vendor', table_name='receipts')
    op.drop_index('idx_receipt_po', table_name='receipts')
    op.drop_index('idx_receipt_number', table_name='receipts')
    op.drop_index('idx_receipt_material', table_name='receipts')
    op.drop_index('idx_receipt_date', table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_id'), table_name='purchase_orders')
    op.drop_index('idx_po_vendor', table_name='purchase_orders')
    op.drop_index('idx_po_status', table_name='purchase_orders')
    op.drop_index('idx_po_number', table_name='purchase_orders')
    op.drop_index('idx_po_material', table_name='purchase_orders')
    op.drop_index('idx_po_date', table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_offers_offer_number'), table_name='offers')
    op.drop_index(op.f('ix_offers_id'), table_name='offers')
    op.drop_index('idx_offer_vendor', table_name='offers')
    op.drop_index('idx_offer_status', table_name='offers')
    op.drop_index('idx_offer_number', table_name='offers')
    op.drop_index('idx_offer_material', table_name='offers')
    op.drop_index('idx_offer_date', table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_vendors_id'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_code'), table_name='vendors')
    op.drop_index('idx_vendor_code', table_name='vendors')
    op.drop_index('idx_vendor_active', table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_materials_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_code'), table_name='materials')
    op.drop_index('idx_material_code', table_name='materials')
    op.drop_index('idx_material_category', table_name='materials')
    op.drop_index('idx_material_active', table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ### 